target-version = "py312"
line-length = 80

[lint]
preview = true
select = [
    "A",
    "E",
    "F",
    "FA",
    "FIX",
    "N",
    "Q",
    "RET",
    "RUF",
    "S",
    "T20",
    "TD",
    "TID",
    "W",
    "D203",
    "D212",
]
fixable = ["ALL"]
unfixable = []
